import Knex from 'knex';

export async function seed(knex: Knex) {
    await knex('books').insert([
        {
            title: 'Cristianismo puro e simples',
            author: 'C.S. Lewis',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51yyuSLfAZL._SX327_BO1,204,203,200_.jpg',
            desc: 'Em um dos períodos mais sombrios da humanidade, a Segunda Guerra Mundial, C.S. Lewis foi convidado pela BBC a fazer uma série de palestras pelo rádio com o intuito de explicar a fé cristã de forma simples e clara. Mais tarde, ajustado pelo próprio Lewis, esse material daria origem a Cristianismo puro e simples, um grande clássico da literatura. Na obra mais popular e acessível de seu legado, Lewis apresenta os principais elementos da cosmovisão cristã, gradativamente conduzindo o leitor a temas mais profundos e complexos, provocando reflexão e debate. Nesta edição especial e com tradução de uma das maiores especialistas em Lewis do Brasil, você vai encontrar as palavras que encorajaram e fortaleceram milhares de ouvintes em tempos de guerra ― e ainda reverberam mais de 70 anos depois.',
            date: '1603053282',
            price: 26.91,
            rating: 4.9,
            page: 288,
            dimension: '21,4 x 14 x 2 cm',
            isbn: '8578601777'
        },
        {
            title: 'Eu, Robô',
            author: 'Isaac Asimov',
            image: 'https://images-na.ssl-images-amazon.com/images/I/41Pj1UfmHWL._SX328_BO1,204,203,200_.jpg',
            desc: 'Um dos maiores clássicos da literatura de ficção científica, Eu, Robô, escrito pelo Bom Doutor, Isaac Asimov foi publicado originalmente em 1950. O livro serviu como base para o roteiro do filme homônimo, no qual Will Smith interpreta o protagonista, o detetive Del Spooner. Porém, a obra é bastante diferente da história apresentada nas telonas. Eu, Robô é um conjunto de nove contos que relatam a evolução dos autômatos através do tempo. É neste livro que são apresentadas as célebres Três Leis da Robótica: os princípios que regem o comportamento dos robôs e que mudaram definitivamente a percepção que se tem sobre eles na própria ciência. Eu, Robô inicia-se com uma entrevista com a Dra. Susan Calvin, uma psicóloga roboticista da U.S Robots & Mechanical.',
            date: '2014-11-24',
            price: 32.90,
            rating: 4.8,
            page: 320,
            dimension: '21 x 13.8 x 2',
            isbn: '978-8576572008'
        },
        {
            title: 'O guia definitivo do mochileiro das galáxias',
            author: 'Douglas Adams',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51X+P0hPkoL._SX343_BO1,204,203,200_.jpg',
            desc: 'Com mais de 15 milhões de exemplares vendidos, a saga de Arthur Dent pela Galáxia conquistou fãs pelo mundo inteiro. O humor ácido e as tramas surreais de Douglas Adams se tornaram ícones de uma geração e seguem fascinando leitores de todas as idades. Reunindo todos os livros da série em uma edição de luxo, O Guia Definitivo do Mochileiro das Galáxias vai levar você por aventuras improváveis. Pegue sua toalha, divirta-se e não entre em pânico!',
            date: '2020-04-24',
            price: 49.90,
            rating: 4.8,
            page: 784,
            dimension: '23.6 x 16.2 x 4.4',
            isbn: '978-8530601492'
        },
        {
            title: 'O guia do mochileiro das galáxias (O mochileiro das galáxias Livro 1)',
            author: 'Douglas Adams',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51536KWgpWL._SX332_BO1,204,203,200_.jpg',
            desc: 'Considerado um dos maiores clássicos da literatura de ficção científica, O Guia do Mochileiro das Galáxias vem encantando gerações de leitores ao redor do mundo com seu humor afiado.',
            date: '2010-12-15',
            price: 18.71,
            rating: '4.7',
            page: 198,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'O restaurante no fim do universo (O mochileiro das galáxias Livro 2)',
            author: 'Douglas Adams',
            image: 'https://m.media-amazon.com/images/I/51CU2FfZ0AL.jpg',
            desc: 'O que você pretende fazer quando chegar ao Restaurante no Fim do Universo? Devorar o suculento bife de um boi que se oferece como jantar ou apenas se embriagar com a poderosa Dinamite Pangaláctica, assistindo de camarote ao momento em que tudo se acaba numa explosão fatal?',
            date: '2010-12-15',
            price: 20.89,
            rating: 4.5,
            page: 240,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'A vida, o universo e tudo mais (O mochileiro das galáxias Livro 3)',
            author: 'Douglas Adams',
            image: 'https://m.media-amazon.com/images/I/516hMNiSQgL.jpg',
            desc: 'Após as loucas aventuras vividas com seus estranhos amigos em O Guia do Mochileiro das Galáxias e O Restaurante no Fim do Universo, Arthur Dent ficou cinco anos abandonado na Terra Pré-Histórica. Mesmo depois de tanto tempo, ele ainda acordava todas as manhãs com um grito de horror por estar preso àquela monótona e assustadora rotina.',
            date: '2010-12-15',
            price: 20.61,
            rating: 4.5,
            page: 240,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Até Mais, e Obrigado Pelos Peixes! (O mochileiro das galáxias Livro 4)',
            author: 'Douglas Adams',
            image: 'https://m.media-amazon.com/images/I/51ISEOYcm+L.jpg',
            desc: 'Depois de oito anos vagando pelos mais insondáveis cantos da Galáxia, Arthur Dent está de volta à Terra e tudo parece estranhamente normal.',
            date: '2010-12-15',
            price: 20.61,
            rating: 4.5,
            page: 240,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Praticamente Inofensiva (O mochileiro das galáxias Livro 5)',
            author: 'Douglas Adams',
            image: 'https://m.media-amazon.com/images/I/51ed75595pL.jpg',
            desc: 'Praticamente Inofensiva é tão polêmico quanto seu criador. Muitos o consideram o último volume da série O Mochileiro das Galáxias e outros afirmam tratar-se de um título independente, que apenas utiliza os mesmos personagens. Parte dessa controvérsia se deve aos 13 anos que separam este livro da primeira aventura de Arthur Dent, já que Adams iniciou a coleção no final dos anos 1970 e somente em 1992 retomou a história.',
            date: '2010-12-15',
            price: 17.53,
            rating: 4.5,
            page: 240,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'As Crônicas de Nárnia. Brochura',
            author: 'C. S. Lewis',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51+2QAB7I+L._SX329_BO1,204,203,200_.jpg',
            desc: 'Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro? O livro que tem tudo isso é "O leão, a feiticeira e o guarda-roupa", escrito em 1949 por Clive Staples Lewis. MasLewis não parou por aí. Seis outros livros vieram depois e, juntos, ficaram conhecidos como "As crônicas de Nárnia".',
            date: '2009-01-08',
            price: 23.65,
            rating: 4.5,
            page: 752,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e a Pedra Filosofal',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/51DgYTEd49L.jpg',
            desc: 'Quando virou o envelope, com a mão trêmula, Harry viu um lacre de cera púrpura com um brasão; um leão, uma águia, um texugo e uma cobra circulando uma grande letra "H".',
            date: '2015-12-08',
            price: 29.90,
            rating: 4.5,
            page: 265,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e a Câmara Secreta',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/51qbxOEtBrL.jpg',
            desc: 'Há uma trama, Harry Potter. Uma trama para fazer coisas terríveis acontecerem na Escola de Magia e Bruxaria de Hogwarts este ano.',
            date: '2015-12-08',
            price: 35.90,
            rating: 4.5,
            page: 299,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e o prisioneiro de Azkaban',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/41prSQnkSiL.jpg',
            desc: 'Bem-vindo ao ônibus Nôitibus Andante, o transporte de emergência para bruxos e bruxas perdidos. Basta esticar a mão da varinha, subir a bordo e podemos levá-lo aonde quiser.',
            date: '2015-12-08',
            price: 29.09,
            rating: 4.5,
            page: 378,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e o Cálice de Fogo',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/511p8jnsATL.jpg',
            desc: 'Harry volta para a Escola de Magia e Bruxaria de Hogwarts para cursar a quarta série. Para surpresa de todos não haverá a tradicional Copa Anual de Quadribol entre Casas. Será substituída pelo Torneio Tribuxo, uma competição amistosa entre as três maiores escolas européias de bruxaria. A competição é dividida em tarefas, cuja finalidade é testar a coragem, o poder de dedução, a perícia em magia e a capacidade de enfrentar o perigo dos campeões.',
            date: '2015-12-08',
            price: 35.89,
            rating: 4.5,
            page: 631,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e a Ordem da Fênix',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/41I1NK83piL.jpg',
            desc: 'Harry não é mais um garoto. Aos 15 anos, continua sofrendo a rejeição dos Dursdley, sua estranhíssima família no mundo dos "trouxas". Também continua contando com Rony Weasley e Hermione Granger, seus melhores amigos em Hogwarts, para levar adiante suas investigações e aventuras. Neste quinto livro da saga, Harry vai enfrentar as investidas de Voldemort sem a proteção de Dumbledore, já que o diretor de Hogwarts é afastado da escola. E vai ser sem a ajuda de seu protetor que o jovem herói enfrentará descobertas sobre a personalidade controversa de seu pai, Tiago Potter, e a já anunciada morte de alguém muito próximo.',
            date: '2015-12-08',
            price: 39.89,
            rating: 4.5,
            page: 830,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e o enigma do Príncipe',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/51o38t7bl+L.jpg',
            desc: 'Harry, longe de ser aquele menino magricela que vivia no quarto debaixo da escada na casa dos tios trouxas, é um dos principais nomes entre aqueles que lutam contra Voldemort, e se vê cada vez mais isolado à medida em que os rumores de que ele é O Eleito, o único capaz de derrotar o Lorde das Trevas, se espalham pelo mundo bruxo. Dois atentados contra a vida de estudantes, a certeza de Harry quanto ao envolvimento de Draco Malfoy com os Comensais da Morte e o comportamento de Snape, suspeito como sempre, adicionam ainda mais tensão ao já inquietante período.',
            date: '2015-12-08',
            price: 35.84,
            rating: 4.5,
            page: 544,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e as Relíquias da Morte',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/51ghFCcQc1L.jpg',
            desc: 'Em Harry Potter e as Relíquias da Morte, o encontro inevitável com Lord Voldemort não pode mais ser adiado. Harry, no entanto, precisa ganhar tempo para encontrar as Horcruxes que ainda estão faltando. E, pelo caminho, descobrir o que são afinal as Relíquias da Morte e como ele pode usá-las contra o Lorde das Trevas. Seguindo as poucas pistas deixadas por Dumbledore, Harry conta apenas com a ajuda dos leais amigos Rony e Hermione. Juntos, eles percorrem lugares nunca visitados, descobrem histórias nebulosas sobre pessoas queridas e acabam por desvendar mistérios que os incomodavam há muito tempo.',
            date: '2015-12-08',
            price: 44.89,
            rating: 4.5,
            page: 623,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Harry Potter e a Criança Amaldiçoada, Partes Um e Dois (Edição Especial do Roteiro de Ensaio)',
            author: 'J.K. Rowling',
            image: 'https://m.media-amazon.com/images/I/51E3r+V4R+L.jpg',
            desc: 'Baseada numa história original escrita por J.K.Rowling, John Tiffany e Jack Thorne, HARRY POTTER E A CRIANÇA AMALDIÇOADA é a oitava história da série Harry Potter e a primeira a chegar aos palcos. A peça teve sua estreia mundial em 30 de julho de 2016 no West End de Londres.',
            date: '2016-10-31',
            price: 18.90,
            rating: 4.5,
            page: 370,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'O poder do hábito: Por que fazemos o que fazemos na vida e nos negócios',
            author: 'Charles Duhigg',
            image: 'https://m.media-amazon.com/images/I/51vJiEaw12L.jpg',
            desc: 'Charles Duhigg, repórter investigativo do New York Times, mostra que a chave para o sucesso é entender como os hábitos funcionam - e como podemos transformá-los.',
            date: '2012-10-01',
            price: 29.90,
            rating: 4.5,
            page: 464,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'Rápido e devagar: Duas formas de pensar',
            author: 'Daniel Kahneman',
            image: 'https://m.media-amazon.com/images/I/41alIv87Z5L.jpg',
            desc: 'Daniel Kahneman, ganhador do Prêmio Nobel de Economia por pesquisas que colocam em xeque a ideia de que a nossa tomada de decisões é essencialmente racional, é um dos mais importantes pensadores do século XXI. Suas ideias tiveram um impacto profundo em muitas áreas, incluindo economia, psicologia, medicina e política, mas é a primeira vez que o autor reúne seus muitos anos de pesquisa e pensamento em um único livro.',
            date: '2012-08-01',
            price: 29.90,
            rating: 4.5,
            page: 641,
            dimension: 'xxxxxx',
            isbn: 'xxxxxx'
        },
        {
            title: 'O temor do sábio',
            author: 'Patrick Rothfuss',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51YG16TP6LL._SX346_BO1,204,203,200_.jpg',
            desc: 'Nothing to say yet',
            date: '1603053282',
            price: 35.91,
            rating: '4.5',
            page: 500,
            dimension: '9x9x9',
            isbn: '0000'
        },
        {
            title: 'A música do silêncio',
            author: 'Patrick Rothfuss',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51G92GMIluL._SX346_BO1,204,203,200_.jpg',
            desc: 'Nothing to say yet',
            date: '1603053282',
            price: 16.05,
            rating: '4.5',
            page: 500,
            dimension: '9x9x9',
            isbn: '0000'
        },
        {
            title: 'O último reino',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51vXJ-jaDaL._SX333_BO1,204,203,200_.jpg',
            desc: 'O último reino é o primeiro romance das Crônicas Saxônicas, que inspirou a série da Netflix The last kingdom. A saga conta a história de Alfredo, o Grande, e seus descendentes. Com um pano de fundo histórico sensacional, a saga leva o leitor a uma viagem pela formação da atual Inglaterra, as invasões vikings e o embate entre cristianismo e paganismo.Aqui, Bernard Cornwell reconstrói a saga do monarca que livrou o território britânico da fúria dos vikings pelos olhos do órfão Uhtred, que aos 9 anos se tornou escravo dos guerreiros no norte. Nascido na aristocracia da Nortúmbria no século IX, Uhtred é capturado e adotado por um dinamarquês. Nas gélidas planícies do norte, ele aprende o modo de vida viking. No entanto, seu destino está indissoluvelmente ligado a Alfredo, rei de Wessex, e às lutas entre ingleses e dinamarqueses.Aos 11 anos a lealdade de Uhtred é de fato colocada a prova, dividido entre a liberdade do estilo de vida dos vikings e o lado inglês da guerra o protagonista, ele precisa tomar uma decisão.A narrativa de O último reino mostra cenas de batalhas descritas com primazia e reviravoltas cheias de ação e suspense. Apresentando os elementos que consagraram o autor: história e aventura na dose exata. Uma fábula sobre guerra e heroísmo que encanta do início ao fim.The Last Kingdom, série televisiva baseada em Crônicas Saxônicas, teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2006-11-10',
            price: 38.61,
            rating: '4.8',
            page: 364,
            dimension: '22.8x15.6x2.2',
            isbn: '978-8501073525'
        },
        {
            title: 'O cavaleiro da morte',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51YYHsUyDKL._SX334_BO1,204,203,200_.jpg',
            desc: 'O cavaleiro da morte é o segundo volume das Crônicas Saxônicas, saga que inspirou a série da Netflix The last kingdom. A sequência narrada pelo autor Bernard Cornwell conta, pelo ponto de vista de Uhtred, a história do lendário Alfredo, o Grande, e de seus descendentes.Uhtred é um saxão cuja herança foi usurpada. Está a deriva num mundo de fogo e traições e precisa fazer uma escolha: lutar pelos vikings, que o criaram, ou por Alfredo, Rei dos saxões, que o odeia.O que se conta em O cavaleiro da morte apresenta é a história do lendário Alfredo, o Grande, e de seus descendentes. A sequência começa no dia seguinte aos eventos de O último reino, primeiro volume da série, se mostrando um belíssimo relato de lealdades divididas, amor relutante e heroísmo desesperado.São tempos terríveis para os saxões. Derrotados pelos vikings, Alfredo e seus seguidores sobreviventes procuram refúgio em Æthelingæg, a região a que ficou reduzido o reino de Alfredo. Aí, encobertos pela neblina, viajam em pequenos barcos entre as ilhas na esperança de se reagruparem, e encontrarem mais apoio. Porém o abandono dos lordes ingleses, que acabam se aliando aos dinamarqueses, torna tudo mais difícil.Ao reunir o Grande Exército, os vikings têm apenas uma ambição: conquistar Wessex. Quando atacam em uma escuridão impiedosa, Uhtred se vê surpreendentemente do lado de Alfredo. Aliados improváveis: um rei cristão devoto e um pagão que vive da espada. Alfredo é um erudito; Uhtred, um guerreiro cheio de arrogância. No entanto, a desconfortável aliança é forjada e os conduzirá dos pântanos para a colina íngreme, onde o último exército saxão lutará pela existência da Inglaterra.Cornwell relata de forma nua e crua as intempéries do período medieval, revela os podres da justiça e as alianças forjadas por interesses escusos, narra a movimentação do clero e da nobreza que agiam com pouquíssimo ou, até mesmo, sem nenhum pudor. O autor ainda nos mostra como as decisões políticas acabam por culminar em uma guerra sangrenta de proporções arrasadoras.The Last Kingdom, série televisiva baseada em Crônicas Saxônicas, teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2007-05-25',
            price: 38.61,
            rating: '4.8',
            page: 392,
            dimension: '22.8x15.6x2.2',
            isbn: '978-8501075529'
        },
        {
            title: 'Os senhores do norte',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51tG86E9bNL._SX333_BO1,204,203,200_.jpg',
            desc: 'Os senhores do norte é uma história poderosa feita de traição, romance e luta. Numa região de conflitos e levantes em que Uhtred, um nortumbriano criado como viking, homem sem terras, guerreiro sem país, se tornou uma esplêndida figura heróica.O terceiro volume das Crônicas Saxônicas, saga de Bernard Cornwell que inspirou a série da Netflix The last kingdom, começa logo após os acontecimentos descritos em O cavaleiro da morte.O ano é 878 e o reino de Wessex de Alfredo está livre dos vikings. Depois de lutar ao lado do rei na batalha que assegurou Wessex como único reino independente da Inglaterra, Uhtred precisa voltar ao norte para vingar a morte do pai adotivo e resgatar a irmã. Para isso, terá de enfrentar seu velho inimigo, Kjartan, um renegado chefe dinamarquês que o espreita na formidável fortaleza de Dunholm.Para Uhtred, a esperança reside na espada. Em seu caminho, encontrará rebelião, caos e medo, e terá como companhia uma freira saxã que deixou para trás a vocação religiosa. Em nome do poder, o jovem da Nortúmbria será traído por um de seus aliados, se tornando escravo... e contará com a inesperada ajuda daquele que um dia odiou. Ele enfim retorna ao Norte para acertar contas e tomar sua vingança há muito adiada, finalmente, na parede de escudo.Os senhores do norte é impressionante na forma. Consegue mostrar ainda mais crueldade e traição do que os volumes anteriores da série, sem mencionar uma inesperada reviravolta na trama.O toque magistral de Cornwell em descrever guerras e guerreiros não o abandonou aqui, e a batalha final é tão satisfatória quanto bárbara e sangrenta. A saga de Uhtred é sombria, o caminho é encharcado de sangue e politicamente incorreto, mas também é animador, comovente e até filosófico. O destino, como somos lembrados repetidamente, é inexorável.The Last Kingdom, série televisiva baseada em Crônicas Saxônicas, teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2007-11-12',
            price: 38.61,
            rating: '4.8',
            page: 350,
            dimension: '23x15.4x2.2',
            isbn: '978-8501078261'
        },
        {
            title: 'A canção da espada',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51dBe4UuijL.jpg',
            desc: 'O ano é 885 e a Inglaterra está em paz, dividida entre o reino dinamarquês ao norte e o reino saxão de Wessex, ao sul. É nesse cenário que se inicia a trama de A canção da espada, o quarto volume das Crônicas Saxônicas, saga de Bernard Cornwell que inspirou a série da Netflix The last kingdom,Uhtred, filho exilado de um senhor da Nortúmbria, guerreiro por instinto, viking por natureza, parece ter encontrado a tranquilidade. Ele é dono de terras, casado e com uma tarefa a cumprir: o rei Alfredo quer manter intacta a fronteira junto ao rio Tâmisa.Mas os problemas aparecem quando uma nova horda de vikings chega para ocupar Londres. O sonho dos guerreiros do norte é conquistar Wessex. E, para isso, eles precisam da ajuda de Uhtred. Alfredo tem outras ideias. Quer que Uhtred expulse os invasores vikings de Londres.É uma época perigosa e Uhtred precisa decidir até que ponto seu juramento o liga ao rei. Outras nuvens de tempestade estão se reunindo. Æthelflaed ― a filha de Alfredo ― está casada, mas uma reviravolta cruel do destino faz com que sua própria existência se torne uma ameaça ao reino de Alfredo. São as lealdades dúbias de Uhtred, meio saxão, meio dinamarquês, que devem agora decidir todo o futuro da Inglaterra.A canção da espada conta a história da criação da Inglaterra e, como todos os outros romances anteriores de Bernard Cornwell, baseia-se em acontecimentos reais. É uma empolgante história de amor, traições e violência, passada numa Inglaterra em meio a lutas e tumultos tremendos. Mas ao mesmo tempo instigada por um pequeno clarão de esperança de que Alfredo, o grande rei de Wessex, possa se mostrar uma força duradoura. Uhtred, o maior guerreiro do rei, tornou-se sua espada, um homem temido e respeitado por toda a extensão do território, seu Senhor da Guerra.The Last Kingdom, série televisiva baseada em Crônicas Saxônicas, teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2008-07-30',
            price: 38.61,
            rating: '4.8',
            page: 350,
            dimension: '22.8x15.4x2.2',
            isbn: '978-8501081490'
        },
        {
            title: 'Terra em chamas',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51BA6SPWtEL._SX334_BO1,204,203,200_.jpg',
            desc: 'Uma fábula sobre guerra e heroísmo que encanta do início ao fim. Terra em chamas é quinto volume de Crônicas Saxônicas, saga de Bernard Cornwell que inspirou a série da Netflix The last kingdom.A história do soberano Alfredo que livrou o território britânico da fúria dos vikings ganha vida pelos olhos do órfão Uthred, que se tornou escravo dos guerreiros no norte. A partir dele ― e de suas aventuras ―, Cornwell tece uma história de lealdades divididas e heroísmo desesperado.Em Terra em chamas seguimos acompanhando o monarca Alfredo, que está com a saúde debilitada. Seu herdeiro ainda é muito jovem. Os inimigos dinamarqueses fracassaram em tomar Wessex, mas agora a vitória parece iminente. Lideradas pelo brutal Harald Cabelo de Sangue, as hordas vikings atacam. Porém o rei tem Uhtred, que inflige aos vikings uma de suas maiores derrotas.No entanto, o gosto da vitória inglesa é ofuscado por uma tragédia que leva Uhtred a jurar nunca mais servir o reino saxão novamente. Agora, o sonho de retomar as terras que lhe são de direito na Nortúmbria parece mais próximo.E para alcançar seu objetivo, o guerreiro se une ao amigo Ragnar e ao antigo inimigo Haesten.Mas o destino tem outros planos. Os dinamarqueses da Ânglia Oriental e os vikings da Nortúmbria pretendem conquistar toda a Inglaterra. A filha de Alfredo então implora pela ajuda de Uhtred, e o guerreiro, incapaz de dizer não, toma a frente do exército derrotado da Mércia, rumo a uma batalha inesquecível num campo encharcado de sangue junto ao Tâmisa.Mais que um escritor de ficção histórica, o inglês Bernard Cornwell ultrapassou a barreira da literatura. E se tornou referência também entre historiadores. Consultor do History Channel, conseguiu unir leitores e eruditos, sem prejudicar sua qualidade narrativa ou o rigor histórico. Na série Crônicas saxônicas, ele narra a trajetória de Alfredo de tal forma, que é impossível conjurar a imagem do monarca antes de Cornwell.Devido ao grande sucesso e precioso teor histórico, a saga Crônicas Saxônicas deu origem a série televisiva The Last Kingdom, que teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2010-05-17',
            price: 38.61,
            rating: '4.8',
            page: 378,
            dimension: '23x15.4x2.2',
            isbn: '978-8501089984'
        },
        {
            title: 'Morte dos reis',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51Gd14rSbXL._SX334_BO1,204,203,200_.jpg',
            desc: 'Do autor de As crônicas de Artur, Morte dos reis é o sexto volume de Crônicas Saxônicas, saga de Bernard Cornwell que inspirou a série da Netflix The last kingdom.O amado rei Alfredo está em seu leito de morte. Vendo os dias do soberano se aproximarem do fim, a nobreza saxônica está inquieta: o herdeiro ao trono, príncipe Eduardo, não possui a mesma popularidade do pai, e seus inimigos são numerosos.Essa situação dá início a um momento de tensão e incertezas no reino, além de abrir as portas para eventuais traições.Uhtred, braço direito do rei, assume para si a responsabilidade de manter o país em ordem enquanto os problemas a respeito da sucessão não se resolvem, mas não é só com os traiçoeiros inimigos do reino e com os vikings que ele deve se preocupar. Sua relação cada vez mais intensa com a filha de Alfredo, Aethelflaed, o consome cada vez mais, apesar da proibição desse amor. E é preciso estar preparado, pois as rivalidades e intrigas de poder parecem estar caminhando para um desfecho sangrento. Enquanto candidatos à coroa surgem a todo momento, os vikings, antigos adversários dos saxões, se preparam para aproveitar a instabilidade em Wessex e atacar o reino rival.Mas Alfredo fará de tudo para garantir que a paz que instaurou em seu território perdure após sua morte. Para isso, ele conta com Uhtred, guerreiro saxão que o serve há anos. A relação de desconfiança e ao mesmo tempo admiração estabelecida entre os dois tornou-se ainda mais complexa depois de tantos anos de batalhas e discordâncias pessoais.É vontade do rei que Uhtred jure lealdade a seu filho Eduardo, mas o guerreiro tem outros planos: expulsar definitivamente a ameaça viking da Britânia. Sua obstinação o levará a confrontar velhos inimigos e a ressuscitar antigas rivalidades. Porém cada passo em seu caminho parece esconder uma cilada.Devido ao grande sucesso e precioso teor histórico, a saga Crônicas Saxônicas deu origem a série televisiva The Last Kingdom, que teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2012-05-31',
            price: 38.61,
            rating: '4.8',
            page: 378,
            dimension: '23x15.4x2.2',
            isbn: '978-8501098306'
        },
        {
            title: 'O guerreiro pagão',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51EkLDQK5yL._SX335_BO1,204,203,200_.jpg',
            desc: 'Em O Guerreiro Pagão, o consagrado autor britânico de romances históricos Bernard Cornwell, conta o ousado plano de Uhtred, um dos últimos senhores pagãos entre os saxões, de recuperar a fortaleza Bebbanburg das mãos de seu tio usurpador. Este é o sétimo volume de Crônicas Saxônicas, saga de Bernard Cornwell que inspirou a série da Netflix The last kingdom.Atacado pela Igreja, por seus seguidores, sem suas terras e com poucos homens, a missão de Uhtred não será fácil, mas ele tem a oportunidade de uma vez por todas de selar o destino da Britânia e de sua rivalidade com Cnut.Os dias de glória do protagonista parecem pertencer ao passado. A Britânia mergulhou numa paz repleta de tensão e, embora a ameaça dinamarquesa ainda esteja presente, nenhum dos lados do conflIto parece disposto a arriscar um confronto capaz de destruir tudo ao redor. Longe do campo de batalha, o próprio Uhtred sente-se envelhecido e inapto a mudar sozinho os rumos de uma rivalidade que se estende por gerações.Porém, as Nornas, mais uma vez, tecem a tapeçaria do destino e mudam a jornada do guerreiro.Após um acidente, Uhtred, um dos últimos senhores pagãos entre os saxões, se vê hostilizado como nunca pela Igreja, cujo poder só aumenta. Desprovido de posses e aliados, ele se apega às antigas crenças, à habilidade na guerra e ao poder de seu nome para sobreviver em um mundo que voltou a se tornar agressivo de um dia para o outro.Sua única esperança é concretizar um plano ousado e arriscado: recuperar, contando com apenas alguns homens, Bebbanburg, a fortaleza onde cresceu, legado deixado por seu pai e usurpado por seu tio muitos anos antes.O que Uhtred não sabe é que sua missão pessoal vai colocá-lo em meio a um perigoso ardil, capaz de reacender o confronto entre saxões e dinamarqueses e levá-los de volta à matança em uma batalha que selará o futuro da Britânia.Devido ao grande sucesso e precioso teor histórico, a saga Crônicas Saxônicas deu origem a série televisiva The Last Kingdom, que teve sua estreia em 2015 pela BBC. Já a segunda temporada foi coproduzida pela Netflix que, a partir daí, começou a também transmitir a série via streaming. Na produção podemos acompanhar as aventuras do protagonista Uhtred em busca da sua identidade nesta grande guerra.',
            date: '2014-07-01',
            price: 38.61,
            rating: '4.8',
            page: 336,
            dimension: '23x15.4x2.2',
            isbn: '978-8501102386'
        },
        {
            title: 'O trono vazio',
            author: 'Bernard Cornwell',
            image: 'https://images-na.ssl-images-amazon.com/images/I/51Qrhc5eQaL._SX334_BO1,204,203,200_.jpg',
            desc: 'Do autor de As crônicas de Artur, o oitavo volume da série Crônicas Saxônicas As forças de Wessex e da Mércia se juntaram para combater os dinamarqueses, mas a instabilidade da união e a ameaça dos ataques dos reinos pagãos vizinhos são um perigo para a Britânia, pois Æthelred, o senhor da Mércia, está à beira da morte e não tem herdeiros, o que abre caminho para disputas pelo trono. Uhtred de Bebbanburg, o maior guerreiro da Mércia, sempre apoiou a senhora Æthelflaed para que se tornasse a sucessora do trono, mas será que a nobreza aceitará uma mulher como líder? Mesmo ela sendo a viúva de Æthelred e irmã do rei de Wessex? Enquanto os mércios travam brigas internas e os saxões ocidentais tentam anexar o reino aliado, novos inimigos surgem na fronteira norte. Os saxões precisam desesperadamente de uma liderança forte, mas, em vez disso, lutam por um trono vazio, ameaçando arruinar todos os esforços para unir e fortalecer seu reino.',
            date: '2015-07-31',
            price: 38.61,
            rating: '4.8',
            page: 336,
            dimension: '23x15.4x2.2',
            isbn: '978-8501105295'
        },
    ])
}